name: CNVM-CI
permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+"
    types: [opened, synchronize, reopened]

jobs:
  Run-CNVM-Tests:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init Hermit
        run: ./bin/hermit env -r >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Build cloudbeat binary
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: build

      - name: Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 8.8.0
          security-enabled: false

      - name: Run cloudbeat CNVM
        env:
          ES_HOST: http://localhost:9200
          ES_USERNAME: elastic
          ES_PASSWORD: changeme
        run: |
          ./cloudbeat -c deploy/vulnerability/cloudbeat-vuln-mgmt.yml -d '*' &

      - name: Check for vulnerabilities
        run: |
          poetry run pytest -k "cnvm"

      - name: Upload cloudbeat logs
        uses: actions/upload-artifact@v2
        with:
          name: cloudbeat-logs
          path: logs/cloudbeat*

